### ISSUE TITLE
Error creating network

### ISSUE THREAD

**Issue by afroisalreadyinu** [afroisalreadyinu/miniboss#1]
```
Traceback (most recent call last):
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/networks/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./miniboss-main.py", line 216, in <module>
    miniboss.cli()
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ulas/projects/miniboss/miniboss/cli.py", line 31, in start
    exclude, network_name, timeout)
  File "/home/ulas/projects/miniboss/miniboss/services.py", line 248, in start_services
    network = docker.create_network(network_name)
  File "/home/ulas/projects/miniboss/miniboss/docker_client.py", line 34, in create_network
    network = self.lib_client.networks.create(network_name, driver="bridge")
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/models/networks.py", line 156, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/api/network.py", line 153, in create_network
    return self._result(res, json=True)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ulas/.virtualenvs/ostkreuz-testing/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network")
```

**Comment by afroisalreadyinu** [comment]
Apparently related to having a VPN open, more related to docker.
